<?php

namespace Database\Seeders;

use App\Models\LoanProduct;
use Illuminate\Database\Seeder;

class LoanProductSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'slug' => 'rem',
                'name' => 'REM (Real Estate Mortgage)',
                'description' => 'Long-term financing secured by real property title.',
                'interest_rate' => 3.88,
                'rate_type' => 'monthly',
                'collateral' => 'Title',
                'requirements' => 'Valid title, proof of income, appraisal.',
                'max_term' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'blue',
                'icon_key' => 'home',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => null,
                'sort_order' => 10,
            ],
            [
                'slug' => 'chm',
                'name' => 'CHM (Chattel Mortgage)',
                'description' => 'Vehicle and movable asset financing.',
                'interest_rate' => 3.88,
                'rate_type' => 'monthly',
                'collateral' => 'OR/CR',
                'requirements' => 'Vehicle documents, insurance.',
                'max_term' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'blue',
                'icon_key' => 'vehicle',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => null,
                'sort_order' => 20,
            ],
            [
                'slug' => 'salary-aci',
                'name' => 'Salary Loan (Employees ACI)',
                'description' => 'Payroll-based lending for ACI employees.',
                'interest_rate' => 1.5,
                'rate_type' => 'monthly',
                'collateral' => 'Salary Deduction',
                'requirements' => 'Employment certificate, payroll enrollment.',
                'max_term' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'green',
                'icon_key' => 'briefcase',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => null,
                'sort_order' => 30,
            ],
            [
                'slug' => 'travel-abroad',
                'name' => 'Travel Assistance (Work Abroad)',
                'description' => 'Support for documented overseas workers.',
                'interest_rate' => 3.5,
                'rate_type' => 'monthly',
                'collateral' => 'Landbank Account',
                'requirements' => 'Requirement: Landbank account, employment contract abroad.',
                'max_term' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'orange',
                'icon_key' => 'plane',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => null,
                'sort_order' => 40,
            ],
            [
                'slug' => 'sss-gsis',
                'name' => 'SSS/GSIS (Pensioner Loan)',
                'description' => 'For pensioners with SSS or GSIS pension.',
                'interest_rate' => 2.24,
                'rate_type' => 'monthly',
                'collateral' => 'ATM Card',
                'requirements' => 'Valid pension ID, ATM for collateral.',
                'max_term' => 36,
                'age_limit' => 70,
                'safe_age' => 65,
                'downpayment' => null,
                'status' => 'active',
                'tier' => 'green',
                'icon_key' => 'shield',
                'sample_monthly_pension' => 4000,
                'sample_computation_note' => 'Illustrative only; final amount subject to credit evaluation.',
                'calculator_config' => [
                    'pension_multiplier' => 10,
                    'max_principal' => 500000,
                ],
                'sort_order' => 50,
            ],
            [
                'slug' => 'appliance',
                'name' => 'Appliance Loan',
                'description' => 'Retail financing for appliances and electronics.',
                'interest_rate' => 3.88,
                'rate_type' => 'monthly',
                'collateral' => 'Retail partner hold-out',
                'requirements' => 'Valid ID, proof of address.',
                'max_term' => null,
                'age_limit' => null,
                'safe_age' => null,
                'downpayment' => '15% of SRP',
                'status' => 'active',
                'tier' => 'orange',
                'icon_key' => 'appliance',
                'sample_monthly_pension' => null,
                'sample_computation_note' => null,
                'calculator_config' => null,
                'sort_order' => 60,
            ],
        ];

        foreach ($rows as $row) {
            LoanProduct::updateOrCreate(['slug' => $row['slug']], $row);
        }
    }
}
